services:
  database:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - ${PGADMIN_PORT}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - internal
  
  frontend:
    image: 'ghcr.io/${OWNER}/frontend:latest'
    build: 
      context: frontend
    pull_policy: build
    environment:
      VITE_BASE_URL: /
      VITE_API_URL: /api/afisha
      VITE_CDN_URL: /content/afisha
    volumes:
      - frontend_build:/app/dist
    depends_on:
      database:
        condition: service_healthy
  
  migrations:
    image: 'ghcr.io/${OWNER}/backend:latest'
    build:
      context: backend
    pull_policy: build
    command: ["npm", "run", "migrate:up"]
    environment:
      DATABASE_DRIVER: ${DATABASE_DRIVER}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal
      
  backend:
    image: 'ghcr.io/${OWNER}/backend:latest'
    build: 
      context: backend
    pull_policy: build
    environment:
      PORT: ${BACKEND_PORT}
      DEBUG: ${DEBUG}
      DATABASE_DRIVER: ${DATABASE_DRIVER}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - ${BACKEND_PORTS}
    networks:
      - internal
    depends_on:
      database:
        condition: service_healthy
  
  server:
    image: 'ghcr.io/${OWNER}/server:latest'
    build: 
      context: nginx
    pull_policy: build
    ports:
      - ${SERVER_PORTS}
    volumes:
      - frontend_build:/var/www
    depends_on:
      - frontend
      - backend
    networks:
      - internal

volumes:
  db_data:
  pgadmin_data:
  frontend_build:

networks:
  internal: